### ISSUE TITLE
Refactoring main code

### ISSUE THREAD

**Issue by sashaok123** [axsddlr/civitai_downloader#1]
I did a little refactoring of your main code.
[mainV2.zip](https://github.com/axsddlr/civitai_downloader/files/10812800/mainV2.zip)

**Comment by axsddlr** [comment]
I appreciate the help and some changes. If you can next upload a pull request. 
Also i dont intend to pass the api key as a function parameter however i can change how i implement it.

also your refractoring removed a majority of my code unless you wanted to only give me a diff of your changes.

thank you
