### ISSUE TITLE
Found 0 Models

### ISSUE THREAD

**Issue by mindsailor** [axsddlr/civitai_downloader#2]
I followed setup steps, saved config with api key to config.json etc.    however when I run nothing seems to happen when I run with python main.py --verbose I get the following.  Any help is much appreciated, thank you!  

==================================================
       Running civitai_download.py v0.0.2
==================================================

Found 0 models

**Comment by axsddlr** [comment]
do you have anything liked on civitai? make sure you properly put api key in config,json. I have 0 issues with finding models

**Comment by mindsailor** [comment]
I did go like something just to see, I'm not sure if I had previously, but it didn't seem to help unfortunately.  I have config.json set-up with api key same as examples without "<>".  I have tried multiple keys and I have also tried on Colab with the same result of 0.  
This machine is Windows running python 3.10.6 if that helps at all. 

Thank you.

**Comment by axsddlr** [comment]
> I did go like something just to see, I'm not sure if I had previously, but it didn't seem to help unfortunately. I have config.json set-up with api key same as examples without "<>". I have tried multiple keys and I have also tried on Colab with the same result of 0. This machine is Windows running python 3.10.6 if that helps at all.
> 
> Thank you.

interesting, i will need to add more logging to the code and see where it would fail in gathering models, need thing would be try using cookies token

**Comment by mindsailor** [comment]
I went and Loved and 5 stared several more items and it suddenly started working.  Thank you.

**Comment by axsddlr** [comment]
The intent of the api key is to use your likes from the site to download
the model

**Comment by mindsailor** [comment]
Yeah, I missed that somehow sorry about that.
